### ISSUE TITLE
Adding Browser Balena Block to be able to see the dashboard on a connected monitor or display

### ISSUE THREAD

**Issue by moe-sani** [balena-io-playground/internetspeedtest#20]
Hi
I wonder if there is any plans for adding in the display support?
Right now you are only able to see the results on a webpage, but what if someone wants to see the dashbord on a monitor connected to the RaspberryPi? 
This could be done by adding in the balena browser block which will lunch the chromium in a kiosk mode.
I am happy to make a pull request if needed.

regards
Moe

**Comment by phil-d-wilson** [comment]
Hey @moe-sani ,

Thanks for the suggestion, but this wouldn't be something I would add to this repo. You're right that people just need to add the browser block to they compose file. So I would prefer to keep this repo light, and if people want an attached screen they can drop in the browser block. It's ~800mb so I think it's best to let people pull that in only if they need it.

Phil

**Comment by moe-sani** [comment]
Hi @phil-d-wilson 
Thanks for getting back to me very quickly!
Yes you are right! it makes sense!

I have just tried adding display support in my local rig now and it works well by just dropping in browserblock in dockercompose.

Its very simple, but for those who just want a plug and play experience, do you think I can make this (as a separate repository) available in balenaHub?

Let me know if you have any suggested ways to proceed.

BTW, I forgot to thank you for the great project! It's extremely useful piece of software!

Moe

**Comment by phil-d-wilson** [comment]
@moe-sani 

> do you think I can make this (as a separate repository) available in balenaHub?

Absolutely! If you find it helpful to have this app and the browser block used together, then someone else surely will too! You can add your creation as a fleet or a project by following this: https://hub.balena.io/submit
Thanks for contributing!

Phil
