### ISSUE TITLE
Interim dashboard sync skipped: No schema found

### ISSUE THREAD

**Issue by pranasziaukas** [balena-io-playground/internetspeedtest#5]
Running RPi4 on balenaOS 2.65.0+rev1, as initialized by hub.balena.io, this project does not work for me out of the box in the sense that there are no dashboards to see on Grafana.
I'm running on wifi at the moment, but the problem seems to be more with the Grafana setup as indicated by the `Interim dashboard sync skipped: No schema found`.

The device logs are looping
```
04.01.21 17:28:33 (+0200)  influxdb  2021-01-04T15:28:33.032493Z   info     Executing query {"log_id": "0RVUjSH0xxx", "service": "query", "query": "SELECT fieldKey, fieldType FROM balena.autogen._fieldKeys"}
04.01.21 17:28:33 (+0200)  influxdb  [httpd] 172.17.0.3 - - [04/Jan/2021:15:28:33 +0000] "GET /query?db=balena&q=show+field+keys HTTP/1.1" 200 33 "-" "Python-urllib/3.9" 81437e3f-4ea1-11eb-808e-0242ac110xxx 2403
04.01.21 17:28:33 (+0200)  dashboard  Interim dashboard sync skipped: No schema found.
```

**Comment by pranasziaukas** [comment]
Everything works if I use `balena push` though. Should this issue be moved somewhere else closer to balenaHub?

**Comment by swanserquack** [comment]
I'm having the same issue with my project setup as well and it constantly loops and doesn't update the dashboard.

06.01.21 17:00:46 (+0000)  dashboard  Interim dashboard sync skipped: No schema found.

**Comment by swanserquack** [comment]
Turns out you just have to wait a bit and it will fix itself.

**Comment by Mat15011** [comment]
Have you found any solution?

**Comment by swanserquack** [comment]
My solution was just to let it sit for about 10 minutes, reboot it and then wait and it will fix itself.

**Comment by Mat15011** [comment]
Which version balena? Which Hardware? Which connectivity?

**Comment by swanserquack** [comment]
Balena Version:2.65.0
Hardware:Raspberry Pi 4
Connectivity:Wifi

**Comment by Mat15011** [comment]
Any ideas why it's not still working... i'm exactly on the same setup as @swanserquack. It's looklike the DB are not able to write down data or the dashboard can't read the DB 

Can you help me @phil-d-wilson

**Comment by phil-d-wilson** [comment]
@Mat15011 sure, I'll take a look tomorrow and see if I can recreate your issue.

**Comment by laziob** [comment]
Same issue here.

Running on 
Balena Version: balenaOS 2.58.3+rev1
Hardware BalenaFin
Connectivity: Wifi

**Comment by cornflakes** [comment]
Same issue here.

Balena version: balenaOS 2.67.3+rev4
HW: RaspberryPi 3b+
Connectivity: LAN

Could it be linked to this:
https://github.com/eclipse/mosquitto/issues/2079

**Comment by pranasziaukas** [comment]
> My solution was just to let it sit for about 10 minutes, reboot it and then wait and it will fix itself.

I definitely waited more than 10 minutes, and then rebooted at least once.

It probably depends on when exactly the database schema is (should be) created.

**Comment by phil-d-wilson** [comment]
I've found the issue - MQTT has introduced a breaking change. I'm working on the fix now.

**Comment by phil-d-wilson** [comment]
All - I have a temporary fix for this issue, which I'm about to merge: I've pinned the version of MQTT to 1.6 so this app works just like it used to. However I have also raised an issue to fix this properly by moving to version 2:

https://github.com/balenalabs-incubator/internetspeedtest/issues/10

**Comment by laziob** [comment]
Awesome thanks Phil. And mind my ignorance but for applying this fix we should Deploy it With balena again right?

**Comment by phil-d-wilson** [comment]
@laziob yep - you have use the deploy button again (if that's how you deployed it before) and use your existing application as the target.

**Comment by ianog-eng** [comment]
@phil-d-wilson I'm still having this issue, having deployed a new device from scratch, how do I include the fix?
